version: '2.1'
services:
  appsvr:
    image: payara/server-full:5-SNAPSHOT
    ports:
     - "80:8080"
    volumes:
     - "./target/ks.war:/opt/payara5/glassfish/domains/domain1/autodeploy/ks.war"
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/ks/resources/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
